name: update-lambda

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
  pull_request:
    branches:
    - master

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: AWS
          dest: lambda.zip
  lambda:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - run: echo "THIS IS A TEST PACKAGE" > file.txt
      - run: zip lambda.zip file.txt
      - uses: ./yvesgurcan/deploy-lambda-function
        with:
          package: lambda.zip
          function-name: TEST-FUNCTION
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: us-west-2
