name: update-lambda

on:
  push:
    branches:
    - master
    paths-ignore:
    - '*.md'
    - '*.yml'
  pull_request:
    branches:
    - master

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Zip folder
      uses: papeloto/action-zip@v1
      with:
        files: AWS
        dest: AWS/lambda.zip

    - name: Upload Zip file
      uses: actions/upload-artifact@v2
      with:
        name: lambda.zip
        path: AWS/lambda.zip
    
    - name: Download Zip file
      uses: actions/download-artifact@v2
      with:
        name: AWS/lambda.zip

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Run
      run: |
        aws lambda update-function-code \
          --function-name  product-availability-checker \
          --zip-file fileb://lambda.zip
