name: update-lambda

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
  pull_request:
    branches:
    - master

jobs:
  
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: AWS
          dest: lambda.zip
  
  lambda:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master

      - name: Run-1
        run: echo "THIS IS A TEST PACKAGE" > file.txt
        
      - name: Run-2
        run: zip lambda.zip file.txt

      - name: Update
        uses: ./stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: TEST-FUNCTION
          AWS_REGION: us-west-2
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
