name: update-cloud-functions

on:
  push:
    branches:
    - master
    paths:
    - 'GCP/main.py'
    - '.github/workflows/update-cloud-functions.yml'
  pull_request:
    branches:
    - master

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
     
    - name: Run
      run: |
        gcloud functions deploy product-availability-checker \
          --region us-west2 \
          --source https://source.developers.google.com/projects/product-availability-checker/repos/github_gdmoney_product-availability-checker/moveable-aliases/master/paths/GCP
